#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> [subdomain]

domain="$1"
subdomain="$2"

display_info() {
    local sub="$1"
    local domain="$2"
    local info=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:')
    if [ -z "$info" ]; then
        echo "Subdomain $sub does not exist."
    else
        local record_type=$(echo $info | awk '{print $7}')
        local destination=$(echo $info | awk '{print $8}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    fi
}

subdomains=("www" "lb-01" "web-01" "web-02")

if [ -n "$subdomain" ]; then
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    display_info "$sub" "$domain"
done
