#!/usr/bin/env bash
#  configures a brand new Ubuntu machine

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/server_name _;/a \\\tadd_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default
sudo service nginx restart
