#!/usr/bin/env bash
# Installs and configures HAproxy on lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg-default

server1="server 217836-web-01 54.242.192.138:80 check"
server2="server 217836-web-02 3.90.85.81:80 check"
frontend="frontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backend>backend="backend backendnodes\n\tbalance roundrobin\n\t$server1\n\t$server2"

sudo sed -i "$ a $frontend" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a $backend" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
