#!/bin/bash

# Set variables
PASSWORD="$1"
CURRENT_DATE=$(date +"%d-%m-%Y")

# Generate MySQL dump
mysqldump -u root -p"$PASSWORD" --all-databases > backup.sql

# Compress MySQL dump
tar -czvf "${CURRENT_DATE}.tar.gz" backup.sql
