#!/usr/bin/env bash
# Manages a Daemon process

# Function to handle program start
start() {
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
}

# Function to stop the process
stop() {
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
}

# Function to restart the program
restart() {
	stop
	start
}

case "$1" in
    start)
		start
		echo "manage_my_process started"
	;;
    stop)
		stop
		echo "manage_my_process stopped"
	;;
    restart)
		restart
		echo "manage_my_process restarted"
	;;
    *)
		echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
